### PR TITLE
Json Abstraction

### PR DESCRIPTION
**Pull request by darkfrog26**
Major refactoring of scribe-json to abstract JSON implementation and creation of Fabric implementation

### CODE REVIEW

**Comment by GreyPlane** [comment]
Looks good to me, I guess after adding pluggable format code and finishing this work, I can implement the circe integration into scribe.

**Comment by darkfrog26** [comment]
@GreyPlane your PR references DataDog, but I'm thinking that should be a different module entirely as it doesn't really have anything to do with the `scribe-json` functionality since it can't contain arbitrary JSON. Thoughts?

**Comment by GreyPlane** [comment]
> your PR references DataDog



Oh, I may just try to demonstrate the idea about separating data from a certain endpoint, I'm only using LogStash record with FileWriter actually.

> it can't contain arbitrary JSON


I'm not sure what you mean by this, I may think even with a specific record format like DataDog, how to encode it to actual JSON(library-specific) is still should be able to customize which I'm not sure if it is "arbitrary"?

**Comment by darkfrog26** [comment]
> I'm not sure what you mean by this, I may think even with a specific record format like DataDog, how to encode it to actual JSON(library-specific) is still should be able to customize which I'm not sure if it is "arbitrary"?

LogStash supports a `message` that can be any valid JSON, but DataDog takes `text`, which, as the name suggests, is just a string.

**Comment by GreyPlane** [comment]
I may not have enough knowledge of these record formats to get what you said correctly, but the code for DataDog in my previous PR seems to have nothing related to the scribe-json functionality.

**Pull request merged**
