### PR TITLE
feat: +circe json support

### PR DESCRIPTION
**Pull request by GreyPlane**
#392 
#398 
as mentioned, add Circe support.
@darkfrog26, are you ok with this one with hardcoded log record format with JSON implementation and some duplicate code?

### CODE REVIEW

**Comment by darkfrog26** [comment]
Looks good, but you should add it to the root aggregation so it gets built and published properly.

**Comment by darkfrog26** [comment]
Take a look at the test output. It looks like you're using some features that aren't available in Scala 2.12.

**Comment by GreyPlane** [comment]
Wow, I've never written code in Scala 2.12, it looks like it hasn't partitionMap, changed it.

**Comment by darkfrog26** [comment]
Just released `3.11.1` that includes this.

**Pull request merged**
